# https://github.com/verdaccio/docker-examples
version: '3'

services:
  npm-registry:
    container_name: npm.registry
    image: verdaccio/verdaccio
    restart: unless-stopped
    ports:
      - 4873:4873
    volumes:
      - ./app/conf:/verdaccio/conf
      - ./app/storage:/verdaccio/storage
      - ./app/plugins:/verdaccio/plugins
